### ISSUE TITLE
When using minimized view-models, fully charging the lead pipe blocks a good chunk of the screen

### ISSUE THREAD

**Issue by PumpKindOf** [openfortress/public-issue-tracker#44] opened 2022-09-29 00:06 UTC
![Lead Pipe Bug](https://user-images.githubusercontent.com/87558078/192909654-d26afd0a-f829-44cd-b9f6-e6b02c19d372.png)

**Comment by brysondev** [comment] 2023-01-19 00:33
Intentional + if it's that obstructive change view-model positions / use min models. 

Closing as not a bug.

**Closed by brysondev** 2023-01-19 00:33 UTC
