### ISSUE TITLE
Bodygroups not updating when changing cosmetics on Linux.

### ISSUE THREAD

**Issue by TexanDoomGuy** [openfortress/public-issue-tracker#38] opened 2022-09-14 00:20 UTC
When adding cosmetics,the bodygroups don't change. A good example is the chest, it's meant to remove the vest but doesn't and adds the new one anyways. You can see this in the image below.
![screenshot_8](https://user-images.githubusercontent.com/86894317/190031580-432c241d-2a74-46fc-ab4a-040faa1af4a4.png)

This might have something to do with me using Linux, but I'm not sure. I'm using Manjaro if you wanted to know what distro I'm using.

**Comment by brysondev** [comment] 2023-02-18 09:47
This along with issues with respawn particles are being addressed, no ETA and no real updates to provide as of now. I highly suggest using Proton for now since its pretty much fine from my experience.

Leaving this open for now.

**Comment by sapphonie** [comment] 2023-10-30 05:19
Closed as we no longer support linux - reopen if you can reproduce this on proton.

**Closed by sapphonie** 2023-10-30 05:19 UTC
Labels: bug
