### ISSUE TITLE
this is what happens if you have cl_hud_minmode 1 and cl_hud_playerclass_use_playermodel 2 enabled at the same time

### ISSUE THREAD

**Issue by Igarni** [openfortress/public-issue-tracker#5] opened 2022-09-03 10:29 UTC
![image](https://user-images.githubusercontent.com/51513803/188266488-6eb5217f-610e-46dd-9001-d9961326b0a2.png)

**Comment by KaydemonLP** [comment] 2023-06-14 19:33
Fixed internally; Caused by incorrectly assignet res settings.

**Closed by KaydemonLP** 2023-06-14 19:33 UTC
